excluded:
  - Package.swift
  - Carthage
  - .build
  - Sources/SwiftCraft/Network/Crypto/Encryption/SwCrypt.swift

identifier_name:
  excluded:
    - id
    - x
    - y
    - z

disabled_rules:
  - nesting
  - identifier_name

enabled_rules:
  - explicit_acl
  - explicit_init
  - closure_end_indentation
  - conditional_returns_on_newline
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - explicit_enum_raw_value
  - fallthrough
  - implicit_return
  - let_var_whitespace
  - literal_expression_end_indentation
